version: 0.1
phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Pré build phase"
      - gradle clean compile
      - gradle test
      - gradle lint
  build:
    on-failure: ABORT
    commands:
      - echo "Building"
      - gradle generateArtifact
  post_build:
    on-failure: ABORT
    commands:
      - echo "Movendo os arquivos que serão feitos upload"
      - mv build/libs/*.war ./ROOT.war

artifacts:
  files:
    - ROOT.war