version: "3.7"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: abc_tech
    volumes:
      - .:/usr/app
    ports:
      - "3306:3306"
  app:
    build: .
    environment:
      JDBC_CONNECTION_STRING: jdbc:mysql://mysql:3306/abc_tech
      RDS_USERNAME: root
      RDS_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql