server:
  port: 8080

spring:
  datasource:
    url: ${JDBC_CONNECTION_STRING}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

abctech:
  app:
    jwtSecret: 3718293U1I
    jwtCookieName: abctechapi
    jwtExpirationMs: 86400000