server:
  port: 8080

build.name: ${rootProject.name}
build.version: ${version}

spring:
  datasource:
    url: ${JDBC_CONNECTION_STRING}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true