on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: gradle
      - name: Compile
        run: ./gradlew clean compile
      - name: Lint
        run: ./gradlew lint
      - name: Test
        run: ./gradlew test
      - name: Verify code coverage
        run: ./gradlew jacocoTestCoverageVerification
      - name: Build and generate artifact
        run: ./gradlew generateArtifact
      - uses: actions/upload-artifact@v3
        with:
          name: war file
          path: build/libs/*.war
          if-no-files-found: error