on:
  push:
    branches:
      - main

name: CI Release
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Main
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: gradle
      - name: Compile
        run: ./gradlew clean compile
      - name: Lint
        run: ./gradlew lint
      - name: Test
        run: ./gradlew test
      - name: Verify code coverage
        run: ./gradlew jacocoTestCoverageVerification
      - name: Build and generate artifact
        run: ./gradlew generateArtifact
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.war"
          token: ${{ secrets.TOKEN }}
          tag: $${{ steps.version.outputs.content }}
          commit: main
